### ISSUE TITLE
Allow symfony/css-selector 3.* version

### ISSUE THREAD

**Issue by drAlberT** [OpenBuildings/spiderling#17]
Please change the requirements to allow version 3.* too

Thanks

**Comment by EZarkov** [comment]
Done.

**Comment by hkdobrev** [comment]
FWIW the initial fix and discussion started in #18 and was finished in #20.

**Comment by hkdobrev** [comment]
@vuthaihoc I've noticed you've created a fork which supports the new CSSSelector component and published it to Packagist - https://github.com/vuthaihoc/spiderling Now that issue is resolved in the main repo you might find it better to mark your fork as abandoned on Packagist and use `openbuildings/spiderling` again. You'd benefit of future fixes and of the improved tests here with more PHP versions. Also sharing any interesting use cases might be useful! Cheers!
